import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({weight: ['600'], subsets: ['latin']})
export const metadata: Metadata = {
  title: 'Arven Scans',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{overflowX:'hidden'}} className={`${inter.className} ${poppins.className} h-[100vh] text-sm text-white` } >{children}</body>
    </html>
  )
}
